<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <DefineConstants>FABLE_COMPILER</DefineConstants>
    </PropertyGroup>
    <ItemGroup>
        <None Include="index.html" />
        <None Include="vite.config.mts" />
        <None Include="roundtrip.mjs" />
        <Compile Include="RoundTrip.fs" />
        <Compile Include="App.fs" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="../Shared/Shared.fsproj" />
    </ItemGroup>
    <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
